edonation/urls.py
from django.contrib import admin
from django.urls import path
from donation.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('all_logins',all_logins, name='all_logins'),
    path('donor_login',donor_login, name='donor_login'),
    path('volunteer_login', volunteer_login, name='volunteer_login'),
    path('admin_login', admin_login, name='admin_login'),
    path('donor_reg', donor_reg, name='donor_reg'),
    path('donor_home', donor_home, name='donor_home'),
    path('donor_home', donor_home, name='donor_home'),
    path('logout/', Logout, name='logout'),
    path('donate_now', donate_now, name='donate_now'),
    path('donation_history', donation_history, name='donation_history'),
    path('admin_home', admin_home, name='admin_home'),
    path('pending_donation', pending_donation, name='pending_donation'),
    path('view_donationdetail/<int:pid>', view_donationdetail, name='view_donationdetail'),
              ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

donation/models.py
from django.db import models

from django.contrib.auth.models import User

class Donor(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    contact = models.CharField(max_length=15,null=True)
    address = models.CharField(max_length=300,null=True)
    userpic = models.FileField(null=True)
    regdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username


class Volunteer(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    contact = models.CharField(max_length=15,null=True)
    address = models.CharField(max_length=300,null=True)
    userpic = models.FileField(null=True)
    idpic = models.FileField(null=True)
    aboutme = models.CharField(max_length=300, null=True)
    status = models.CharField(max_length=20, null=True)
    regdate = models.DateTimeField(auto_now_add=True)
    adminremark = models.CharField(max_length=300, null=True)
    updationdate = models.DateField(null=True)

    def __str__(self):
        return self.user.username


class DonationArea(models.Model):
    areaname = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=300, null=True)
    creationdate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.areaname

class Donation(models.Model):
    donor = models.ForeignKey(Donor,on_delete=models.CASCADE)
    donationname = models.CharField(max_length=15,null=True, blank=True)
    donationpic = models.FileField(null=True, blank=True)
    collectionloc = models.CharField(max_length=300, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    donationdate = models.DateTimeField(auto_now_add=True)
    adminremark = models.CharField(max_length=300, null=True, blank=True)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE, blank=True)
    donationarea = models.ForeignKey(DonationArea, on_delete=models.CASCADE, blank=True)
    volunteerremark = models.CharField(max_length=300, null=True, blank=True)
    updationdate = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.id

class Gallery(models.Model):
    donation = models.ForeignKey(Donation,on_delete=models.CASCADE)
    deliverypic = models.FileField(null=True)
    creationdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.id

donation/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout

from .models import *
from datetime import date

# Create your views here.

def index(request):
    return render(request, 'index.html')

def all_logins(request):
    return render(request, 'all_logins.html')

def donor_login(request):
    if request.method == 'POST':
        u = request.POST['emailid']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        if user:
            login(request, user)
            error = "no"
        else:
            error = "yes"
    return render(request, 'donor_login.html', locals())

def volunteer_login(request):
    return render(request, 'volunteer_login.html')

def admin_login(request):
    if request.method == 'POST':
        u = request.POST['username']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        try:
            if user.is_staff:
                login(request, user)
                error = "no"
            else:
                error = "yes"
        except:
            error = "yes"

        return render(request, 'admin_login.html', locals())

def donor_reg(request):
    error = ""
    if request.method == "POST":
        fn = request.POST['firstname']
        ln = request.POST['lastname']
        em = request.POST['email']
        contact = request.POST['contact']
        pwd = request.POST['pwd']
        userpic = request.FILES['userpic']
        address = request.POST['address']

        try:
            user = User.objects.create_user(first_name=fn, last_name=ln, username=em, password=pwd)
            Donor.objects.create(user=user,contact=contact,userpic=userpic,address=address)
            error="no"
        except:
            error="yes"
    return render(request, 'donor_reg.html',locals())

def donor_home(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    return render(request, 'donor_home.html')

def donate_now(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    user = request.user
    donor = Donor.objects.get(user=user)
    if request.method=="POST":
        donationname = request.POST['donationname']
        donationpic = request.FILES['donationpic']
        collectionloc = request.POST['collectionloc']
        description = request.POST['description']
        try:
            Donation.objects.create(donor=donor,
                                    donationname=donationname,
                                    donationpic=donationpic,
                                    collectionloc=collectionloc,
                                    description=description,
                                    status="pending")
            error="no"
        except:
            error="yes"
    return render(request, 'donate_now.html', locals())


def Logout(request):
    logout(request)
    return redirect('index')

def donation_history(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    user = request.user
    donor = Donor.objects.get(user=user)
    donation = Donation.objects.filter(donor=donor)
    return render(request, 'donation_history.html', locals())

def admin_home(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    return render(request, 'admin_home.html')


def pending_donation(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    donation = Donation.objects.filter(status="pending")
    return render(request, 'pending_donation.html', locals())

def view_donationdetail(request,pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    donation = Donation.objects.get(id="pid")
    if request.method == "POST":
        status = request.POST['status']
        adminremark = request.POST['adminremark']

        try:
            donation.adminremark = adminremark
            donation.status = status
            donation.updationdate = date.today()
            donation.save()
            error="no"
        except:
            error="yes"

    return render(request, 'view_donationdetail.html', locals())

donation/templates/admin_base.html
{% load static %}
<html>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
  <script src="{% static 'js/myjs.js' %}"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- DATA TABLE END -->
 <title>Donation Management System</title>


<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">

<script>
    $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>
</head>
<body>
<div class="vertical-nav bg-white" id="sidebar">
    <div class="py-4 px-3 mb-1 bg-light">
        <p class="text-center font-weight-bold text-uppercase px-3 small text-dark">Donation management System</p>
        <div class="media d-flex align-items-center">
            <img src="{% static 'images/adminlogo.png' %}" width="80" height="80" class="rounded-circle img-thumbnail">
            <div class="media-body">
                <h4 class="mb-0 text-dark">Admin</h4>
                <p class="text-muted mb-0 text-dark">{{request.user.email}}</p>
            </div>
        </div>
    </div>
    <ul class="nav flex-column bg-white">
        <li class="nav-item">
            <a href="{% url 'admin_home' %}" class="nav-link text-danger bg-light">
                <i class="fas fa-tachometer-alt fa-fw mr-3 text-danger"></i>
                Dashboard
            </a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-danger bg-light" href="#" id="navbardrop">
              <i class="fas fa-chart-bar mr-3 text-danger fa-fw"></i> Donation Management
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">New Donation Request</a>
                <a class="dropdown-item" href="">Manage Services</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-danger bg-light" href="#" id="navbardrop">
              <i class="fas fa-chart-bar mr-3 text-danger fa-fw"></i> Contact Us Queries
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">Unread Queries</a>
                <a class="dropdown-item" href="">Read Queries</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-danger bg-light" href="#" id="navbardrop">
              <i class="fas fa-chart-bar mr-3 text-danger fa-fw"></i> Booking
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">New Booking</a>
                <a class="dropdown-item" href="">Old Booking</a>
            </div>
        </li>
        <li class="nav-item">
            <a href="" class="nav-link text-danger bg-light">
                <i class="fas fa-cog mr-3 text-danger fa-fw"></i>
                Change Password
            </a>
        </li>
        </ul>
</div>
<!--vertical navbar end-->
<div class="page-content p-4" id="content">
    <a href="{% url 'logout' %}" title="logout" class="float-right text-black"><i class="fas fa-sign-out" aria-hidden="true"></i></a>
    <!--toggle btn-->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-black rounded-pill">
    <i class="fas fa-bars mr-2"></i>
    <small class="text-uppercase font-weight-bold">Toggle</small>
    </button>
    <!-- end toggle btn-->
    {% block main %}
    {% endblock %}
</div>
</body>
</html>

donation/templates/admin_home.html
{% extends 'admin_base.html %}

{% block main %}

{% endblock %}

donation/templates/admin_login.html
{% load static %}

<head>


</head>
<body id=login style="background-image:url({% static 'images/background1.png' %})">
{{% include 'navigation.html' %}
<hr class ="mt-0">

<div class="row">
    <div class="col-lg-5 m-auto">
        <div class="card mt-5 bg-dark">
            <div class="card-title text-center mt-3">
                <img src="{% static 'images/adminlogo.png'%}" width="150" height="150">
                <h2 class="text-white">Admin Login</h2>
                </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-user fa-2x"></i>
                            </span>
                        </div>
                        <input type="text" name="username" class="form-control py-4" placeholder="UserName">

                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-lock fa-2x"></i>
                            </span>
                        </div>
                        <input type="password" name="pwd" class="form-control py-4" placeholder="Password">

                    </div>
                    <input type="submit" value="Login" class="btn btn-success px-5">
                    <a href="{% url 'index' %}" class="float-right text-white mt-2">Go Back To Home</a>
                </form>
            </div>
        </div>
    </div>
</div>
</body>

donation/templates/all_logins.html
{% load static %}
<html>
<head>

</head>
<body>
{% include 'navigation.html' %}
<hr class ="mt-0">

<div class="container mt-5">
    <h2 class="text-center">Login As a..</h2>
    <div class="row mt-5">
        <div class="col-lg-4">
            <div class="card" style="width:300px">
                <img src="{% static 'images/donor.png '%}" class="card-img-top" style="width:100%; height:200px">
                <div class="card-body">
                    <h4 class="card-title">Donor</h4>
                    <p class="card-text">Some example text.</p>
                    <a href="{% url 'donor_login' %}" class="btn btn-primary">Go To Donor Login</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card" style="width:300px">
                <img src="{% static 'images/volunteer.png '%}" class="card-img-top" style="width:100%; height:200px">
                <div class="card-body">
                    <h4 class="card-title">Volunteer</h4>
                    <p class="card-text">Some example text.</p>
                    <a href="{% url 'volunteer_login'%}" class="btn btn-primary">Go To Volunteer Login</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card" style="width:300px">
                <img src="{% static 'images/admin.png '%}" class="card-img-top" style="width:100%; height:200px">
                <div class="card-body">
                    <h4 class="card-title">Admin</h4>
                    <p class="card-text">Some example text.</p>
                    <a href="{% url 'admin_login' %}" class="btn btn-primary">Go To Admin Login</a>
                </div>
            </div>
        </div>
    </div>

</div>




</body>
</html>

donation/templates/donate_now.html
{% extends 'donor_base.html' %}

  {% block main %}
<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2 " style="border-bottom:2px solid orange ">Donate Now</h5>
        <div class="container-fluid">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-sm-12">
                        <div class="form-group">
                        <label>Donation Name <span style="color:red">(Note:If you select other please mention detail in description field)</span></label>
                        <select name="donationname" class="form-control" required>
                            <option value="Food Donation">Food Donation</option>
                            <option value="Cloth Donation">Cloth Donation</option>
                            <option value="Footwear Donation">Footwear Donation</option>
                            <option value="Books Donation">Books Donation</option>
                            <option value="Furniture Donation">Furniture Donation</option>
                            <option value="Vessel Donation">Vessel Donation</option>
                            <option value="Toy Donation">Toy Donation</option>
                            <option value="Other">Other</option>
                        </select>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                        <label>Donation Image</label>
                        <input type="file" name="donationpic" class="form-control" required>
                        </div>
                        </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                        <label>Donation Collection Address</label>
                        <textarea name="collectionloc" class="form-control" placeholder="Enter Full Address" required></textarea>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                        <label>Description(Special Note)</label>
                        <textarea name="description" class="form-control" placeholder="Special note for donation  " required></textarea>
                    </div>
                    </div>

                </div>
                <input type="submit" value="Donate Happiness" class="btn btn-danger px-3">
            </form>

        </div>
    </div>

</div>

{% if error == 'no' %}
<script>
    alert('Donation collection request has been sent. We will contact you soon');
    window.location=('{% url 'donation_history' %}');
</script>
{% endif %}

{% if error == 'yes' %}
<script>
    alert('Something went wrong. Please try again');
    </script>
{% endif %}

    {% endblock %}

donation/templates/donation_history.html
{% extends 'donor_base.html' %}

{% block main %}



<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom : 2px solid orange">Donation History</h5>
    <div class="container-fluid">
        <table id="example" class="table table-bordered">
            <thead>
            <tr>
                <th>S.No.</th>
                <th>Donation Name</th>
                <th>Donation Date</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>

            <tbody>
            {% for i in donation %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{i.donationname}}</td>
                <td>{{i.donationdate}}</td>
                <td>{{i.status}}</td>
                <td><a href="#" class="text-primary">View Details</a> </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

    </div>
</div>
{% endblock %}

donation/templates/donor_base.html
{% load static %}
<html>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
  <script src="{% static 'js/myjs.js' %}"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- DATA TABLE END -->
 <title>Donation Management System</title>


<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">

<script>
    $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>
</head>
<body>
<div class="vertical-nav bg-white" id="sidebar">
    <div class="py-4 px-3 mb-1 bg-light">
        <p class="text-center font-weight-bold text-uppercase px-3 small text-dark">Donation management System</p>
        <div class="media d-flex align-items-center">
            <img src="{{request.user.donor_set.all.0.userpic.url}}" width="80" height="80" class="rounded-circle img-thumbnail">
            <div class="media-body">
                <h4 class="mb-0 text-dark">Donor</h4>
                <p class="text-muted mb-0 text-dark">{{request.user.username}}</p>
            </div>
        </div>
    </div>
    <ul class="nav flex-column bg-white">
        <li class="nav-item">
            <a href="{% url 'donor_home' %}" class="nav-link text-danger bg-light">
                <i class="fas fa-tachometer-alt fa-fw mr-3 text-danger"></i>
                Dashboard
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'donate_now' %}" class="nav-link text-danger bg-light">
                <i class="fas fa-tachometer-alt fa-fw mr-3 text-danger"></i>
                Donate Now
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'donation_history' %}" class="nav-link text-danger bg-light">
                <i class="fas fa-tachometer-alt fa-fw mr-3 text-danger"></i>
                Donation History
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-danger bg-light" href="#" id="navbardrop">
              <i class="fas fa-chart-bar mr-3 text-danger fa-fw"></i> Services
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">Add Services</a>
                <a class="dropdown-item" href="">Manage Services</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-danger bg-light" href="#" id="navbardrop">
              <i class="fas fa-chart-bar mr-3 text-danger fa-fw"></i> Contact Us Queries
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">Unread Queries</a>
                <a class="dropdown-item" href="">Read Queries</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-danger bg-light" href="#" id="navbardrop">
              <i class="fas fa-chart-bar mr-3 text-danger fa-fw"></i> Booking
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">New Booking</a>
                <a class="dropdown-item" href="">Old Booking</a>
            </div>
        </li>
        <li class="nav-item">
            <a href="" class="nav-link text-danger bg-light">
                <i class="fas fa-cog mr-3 text-danger fa-fw"></i>
                Change Password
            </a>
        </li>
        </ul>
</div>
<!--vertical navbar end-->
<div class="page-content p-4" id="content">
    <a href="{% url 'logout' %}" title="logout" class="float-right text-black"><i class="fas fa-sign-out" aria-hidden="true"></i></a>
    <!--toggle btn-->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-black rounded-pill">
    <i class="fas fa-bars mr-2"></i>
    <small class="text-uppercase font-weight-bold">Toggle</small>
    </button>
    <!-- end toggle btn-->
    {% block main %}
    {% endblock %}
</div>
</body>
</html>

donation/templates/donor_home.html
{% extends 'donor_base.html' %}
{% block main %}

{% endblock %}

donation/templates/donor_login.html
{% load static %}

<head>


</head>
<body id=login style="background-image:url({% static 'images/background1.png' %})">
{{% include 'navigation.html' %}
<hr class ="mt-0">

<div class="row">
    <div class="col-lg-5 m-auto">
        <div class="card mt-5 bg-dark">
            <div class="card-title text-center mt-3">
                <img src="{% static 'images/adminlogo.png'%}" width="150" height="150">
                <h2 class="text-white">Donor Login</h2>
                </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-user fa-2x"></i>
                            </span>
                        </div>
                        <input type="email" name="emailid" class="form-control py-4" placeholder="Email ID">

                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-lock fa-2x"></i>
                            </span>
                        </div>
                        <input type="password" name="pwd" class="form-control py-4" placeholder="Password">

                    </div>
                    <input type="submit" value="Login" class="btn btn-success px-5">
                    <a href="{% url 'donor_reg' %}" class="float-right text-white mt-2">Create Account <i class="fas fa-angle-double-right"></i></a>
                </form>
            </div>
        </div>
    </div>
</div>
</body>

{% if error == "no" %}
<script>
    alert('Logged In Successful');
    window.location=('{% url 'donor_home' %}');
</script>
{% endif %}

{% if error == "yes" %}
<script>
    alert('Invalid Login Credentials, Try again...');
</script>
{% endif %}

donation/templates/pending_donation.html
{% extends 'admin_base.html' %}

{% block main %}



<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom : 2px solid orange">New Donation Request List</h5>
    <div class="container-fluid">
        <table id="example" class="table table-bordered">
            <thead>
            <tr>
                <th>S.No.</th>
                <th>Donation Name</th>
                <th>Donation Date</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>

            <tbody>
            {% for i in donation %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{i.donationname}}</td>
                <td>{{i.donationdate}}</td>
                <td>{{i.status}}</td>
                <td><a href="{% url 'view_donationdetail' i.id %}" class="text-primary">View Details</a> </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

    </div>
</div>
{% endblock %}